---
galaxy_info:
  author: K3s HA Production
  description: Deploy Longhorn distributed storage
  license: MIT
  min_ansible_version: 2.11
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - kubernetes
    - longhorn
    - storage
    - distributed

dependencies: []