---
galaxy_info:
  author: K3s HA Production
  description: Deploy cert-manager for automated TLS certificates
  license: MIT
  min_ansible_version: 2.11
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - buster
        - bullseye
  galaxy_tags:
    - kubernetes
    - cert-manager
    - tls
    - certificates

dependencies: []